import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGeneratedMigrations1719260018444
  implements MigrationInterface
{
  public readonly name = 'autoGeneratedMigrations1719260018444';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "ToDo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "status" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b287aa0a177c20740f3d917e38f" PRIMARY KEY ("id"))`,
    );
  }

  public async down(): Promise<void> {
    return;
  }
}
