version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: always
    env_file: .env
    environment:
      POSTGRES_PORT: $DATABASE_HOST
      POSTGRES_HOST: $DATABASE_PORT
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
  todo:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
volumes:
  pgdata:
